field: 30663d7d-536d-454c-99fd-820672718f4e # Routes
fieldLayouts:
  48cd0f9b-422d-4668-adae-3f0d93ea9acb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28df0b76-c9f0-4d20-8ca1-a15c637783ea # Route Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f88560a3-b3be-41e9-8529-c23d5a101f70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f819326-c617-42fe-a427-a0c843eb9312 # POI
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70b434f5-03d5-41ee-ab5e-22231d20cd1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acb4d8ea-f708-4993-846b-d1e591d442ff # Cardinal Direction
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9016cede-0391-4462-b501-34c203d9fd6e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c9e44e7-5d22-4316-8ba0-71b48dd8651f
        userCondition: null
fields:
  9f819326-c617-42fe-a427-a0c843eb9312: # POI
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: poi
    instructions: null
    name: POI
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 25
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\User
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\users\UserCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'group:c700366d-c002-43b2-b7ce-f8dd82c7afa8' # Participants
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Users
  28df0b76-c9f0-4d20-8ca1-a15c637783ea: # Route Name
    columnSuffix: fcuvkzgt
    contentColumnType: string(44)
    fieldGroup: null
    handle: routeName
    instructions: 'A name to refer to the route'
    name: 'Route Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 11
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  acb4d8ea-f708-4993-846b-d1e591d442ff: # Cardinal Direction
    columnSuffix: abeqidbj
    contentColumnType: string
    fieldGroup: null
    handle: cardinalDirection
    instructions: null
    name: 'Cardinal Direction'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Group One'
            -
              - value
              - one
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Group Two'
            -
              - value
              - two
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Group Three'
            -
              - value
              - three
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Group Four'
            -
              - value
              - four
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: route
name: Route
sortOrder: 1
