fieldLayouts:
  9e3688e9-e5c8-42d7-a354-bcd73728e7d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 28da74e6-f315-4af1-8060-58a9ad38cd55
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9cf5f394-9490-4101-bdc7-5f09654f53e7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84a19241-4f95-46ff-b113-c7ab94ab0d56
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1972499d-a514-4921-81a0-426f9e57f7b2
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c751597a-3904-43b7-810c-88b36ce7841c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 629498d0-534c-4a2a-996f-82b75a6f1864
            instructions: null
            label: Organizer(s)
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12eff2da-e6df-455c-ba03-dfc7f6af5887
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54d7b784-36c0-4673-ac81-61eb4fec1591
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32a09e2d-b713-460b-8b5e-715fa039ad73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 777e0919-b16b-490f-a586-9bc96baf546d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8397c64e-f64a-40fd-91c5-1512649516a0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f166b0f-35de-422d-b4b1-66441ce46253
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bf9a831-7d5a-4d3d-91bc-cd754537339e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8540a214-8817-45cb-ad75-3f6018d4077e
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 9bc06dfa-790d-40dc-b656-17de5c920ef5
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
