fieldLayouts:
  49731a0b-e69c-4f08-ba86-bff881ab99c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2a3ae702-da84-48d2-af60-456e55aeecc7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1a9f97f9-f026-4cd7-8172-24bc9092c2ad
        userCondition: null
handle: editProfile
hasTitleField: false
name: 'Edit page'
section: cb9b4037-71ad-4f2d-b47e-a020160c2a5c
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
