fieldLayouts:
  89717c42-c2ff-417c-9b18-290eb594ba9a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 46fe8cd5-85e7-44a1-8958-5ee2285eb8eb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ed368ca7-6426-40b6-8826-52708f750704
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 696329c8-d035-43a0-96a8-a66d8626feb9 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
