fieldLayouts:
  99cca0c3-8a61-48b0-9af6-982d409ed4c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: badc9bcc-661c-4812-9863-87217ab4f2f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1a284ed-b660-4132-9e98-a7af09a3cc32 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73b30104-637a-477c-9113-f90ffa9ed951
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60bd3773-a396-438d-896f-49fbfe54e494
        userCondition: null
handle: press
hasTitleField: true
name: Press
section: 994745bc-5470-46e9-9990-b36b218f7269 # Press
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
