allowPublicRegistration: true
deactivateByDefault: true
defaultGroup: ''
photoSubpath: null
photoVolumeUid: b8f74062-ae64-4520-a7ed-fe4272ee4456
requireEmailVerification: true
validateOnPublicRegistration: true
