fieldLayouts:
  31b0ca8b-02de-4b64-8304-5675cf736f29:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: eed121cb-a3e9-49a8-bee4-89739b117310
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aa754956-4c3f-456b-ae21-66e834e5a3c2
        userCondition: null
fs: webFiles
handle: webImages
name: 'Web Images'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: webFiles
transformSubpath: ''
