columnSuffix: tgxigmay
contentColumnType: text
fieldGroup: 1a8a2732-cd82-4bf7-8afe-099fb893ac20
handle: collectiveSuffix
instructions: 'The suffix used for a collection of members, like a hub that are not a hub'
name: 'Collective Suffix'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
