columnSuffix: jvpxqfzp
contentColumnType: string
fieldGroup: e6ea2a09-6abe-4046-8a6f-c483f1d58716 # Common
handle: email
instructions: null
name: Email
searchable: true
settings:
  placeholder: 'E.g. glue.amsterdam@mail.com'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
