columnSuffix: hlkqwyvv
contentColumnType: integer(10)
fieldGroup: 1a8a2732-cd82-4bf7-8afe-099fb893ac20
handle: hubMinimumCount
instructions: 'The minimum amount of participants tied to one location required to form a hub'
name: 'Hub Minimum Count'
searchable: false
settings:
  decimals: 0
  defaultValue: 4
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
