columnSuffix: xafhsdtz
contentColumnType: integer(10)
fieldGroup: 1a8a2732-cd82-4bf7-8afe-099fb893ac20
handle: hubSlideDuration
instructions: 'The duration of each slide on the slideshow when opening a hub popup'
name: 'HUB slide duration'
searchable: false
settings:
  decimals: 0
  defaultValue: 5000
  max: null
  min: 100
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: ms
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
