columnSuffix: noblvuhh
contentColumnType: text
fieldGroup: e6ea2a09-6abe-4046-8a6f-c483f1d58716
handle: largeTextField
instructions: 'An WYSIWYG field allowing for flexible content'
name: 'Large Text Field'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: false
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
