columnSuffix: noblvuhh
contentColumnType: string(16000)
fieldGroup: e6ea2a09-6abe-4046-8a6f-c483f1d58716 # Common
handle: largeTextField
instructions: 'An increased text field allowing for up to 4000 characters'
name: 'Large Text Field'
searchable: false
settings:
  byteLimit: null
  charLimit: 4000
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
