columnSuffix: null
contentColumnType: string
fieldGroup: 1a8a2732-cd82-4bf7-8afe-099fb893ac20 # Map
handle: markerMatrix
instructions: null
name: 'Marker Matrix'
searchable: false
settings:
  contentTable: '{{%matrixcontent_markermatrix}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
