columnSuffix: pfrwwfsg
contentColumnType: text
fieldGroup: 64f81d1c-c242-4549-8d9f-19d9974d28c7 # User
handle: marketingPermissions
instructions: null
name: 'Marketing Permissions'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
