columnSuffix: null
contentColumnType: string
fieldGroup: 014c7b4b-b329-42ff-ba25-1b87cfcadb60 # Navigation
handle: navLinks
instructions: 'A link shown in the navigation pointing to a page'
name: 'Nav Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navlinks}}'
  maxBlocks: 3
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
