columnSuffix: ytnhzofx
contentColumnType: string(200)
fieldGroup: e6ea2a09-6abe-4046-8a6f-c483f1d58716
handle: nTitle
instructions: null
name: Title
searchable: false
settings:
  byteLimit: null
  charLimit: 50
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
