columnSuffix: slugptvz
contentColumnType: string(80)
fieldGroup: e6ea2a09-6abe-4046-8a6f-c483f1d58716
handle: oneWord
instructions: null
name: 'One Word'
searchable: false
settings:
  byteLimit: null
  charLimit: 20
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
