columnSuffix: uuimweku
contentColumnType: string
fieldGroup: e6ea2a09-6abe-4046-8a6f-c483f1d58716 # Common
handle: programType
instructions: null
name: 'Program Type'
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Lecture
        -
          - value
          - lecture
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Workshop
        -
          - value
          - workshop
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Drink
        -
          - value
          - drink
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Guided Tour'
        -
          - value
          - guidedTour
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
