columnSuffix: nqojopcx
contentColumnType: text
fieldGroup: e6ea2a09-6abe-4046-8a6f-c483f1d58716
handle: rsvp
instructions: null
name: Rsvp
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
