dateModified: 1702645036
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      heading: Singles
      type: heading
    -
      key: 'single:76b8abf5-b5a7-4316-b76f-042fd9b0e526' # Map
      type: native
    -
      key: 'single:21c100fa-b14d-4c5a-b30a-f1f28bc91e6d' # Register
      type: native
    -
      key: 'single:8dec35ce-7bad-4407-bbc3-56adc9cccc4a' # Login
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: 'single:cb9b4037-71ad-4f2d-b47e-a020160c2a5c' # Edit page
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: 'single:668738fd-0979-4b4f-9baa-b83f18974c13' # Terms & Conditions
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: 'single:f78b3456-eb39-4e20-9c93-c091a09a1fc4' # Privacy Policy
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      heading: Channels
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:9bc06dfa-790d-40dc-b656-17de5c920ef5' # Program
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
  craft\elements\User:
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: '*'
      tableAttributes:
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      heading: 'Account Type'
      type: heading
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: credentialed
      tableAttributes:
        - email
        - lastLoginDate
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: inactive
      tableAttributes:
        - email
        - 'field:164bc9a4-5b57-4fb1-b7e2-9fb883aebc34' # Phone number
        - dateCreated
      type: native
    -
      heading: Groups
      type: heading
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: admins
      tableAttributes:
        - email
        - lastLoginDate
      type: native
    -
      key: 'group:6f2b710a-6864-4280-8547-363a00213e8e' # Members
      type: native
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: 'group:c700366d-c002-43b2-b7ce-f8dd82c7afa8' # Participants
      tableAttributes:
        - email
        - 'field:164bc9a4-5b57-4fb1-b7e2-9fb883aebc34' # Phone number
        - dateCreated
        - lastLoginDate
      type: native
    -
      key: 'group:51c71de1-cd5f-45b5-8c0f-406dc42a9945' # Founders
      type: native
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: 'group:b7b0394d-62fe-4e1d-9214-0026ddff54bd' # Special Program
      tableAttributes:
        - fullName
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: 'group:d5fda0ac-6099-4e3c-8804-1a5fb5178809' # Hub
      tableAttributes:
        - fullName
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      key: 'group:c6635e8d-466b-4c83-a690-b8d9596ed2ee' # Guests
      type: native
email:
  fromEmail: $SMTP_EMAIL
  fromName: $SMTP_SENDER_NAME
  replyToEmail: $SMTP_EMAIL
  template: ''
  transportSettings:
    host: $SMTP_HOST
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    useAuthentication: '1'
    username: $SMTP_EMAIL
  transportType: craft\mail\transportadapters\Smtp
fs:
  userFiles:
    hasUrls: true
    name: 'User Files'
    settings:
      path: '@webroot/images/uploads/users'
    type: craft\fs\Local
    url: '@web/images/uploads/users'
  webFiles:
    hasUrls: true
    name: 'Web Files'
    settings:
      path: '@webroot/images/uploads/web'
    type: craft\fs\Local
    url: '@web/images/uploads/web'
meta:
  __names__:
    0b32d131-99b5-4a85-8221-f63acc57f704: 'Single Asset' # Single Asset
    0dc72236-a5db-434e-8668-f62c38664692: 'Social Media Link' # Social Media Link
    0e0b993f-64fe-4046-81ae-1ce4800392d8: Locations # Locations
    0edc21c7-41ec-4128-97f9-48fdbc7a3f31: Instagram # Instagram
    1a8a2732-cd82-4bf7-8afe-099fb893ac20: Map # Map
    2acb2572-e11c-42ed-ab36-a86081a1c3e2: 'GLUE Live Headless' # GLUE Live Headless
    2b961231-2dab-4aa1-bb8b-a8aae19bf22f: Lng # Lng
    2e1ecccd-c3ca-4249-b239-5faa3edb6606: City # City
    3f956c2c-f1e6-4abf-abc1-517adbbd0e3d: VAT # VAT
    3f6049f8-db41-426e-86a4-196457c3e028: Slug # Slug
    3fc5f4d1-e130-417e-8f41-29bb276bfbb2: 'Group Three Handle' # Group Three Handle
    5b1e8713-7a27-46ed-a407-e926769d89e2: Colour # Colour
    05b9b1df-40f9-400d-b742-ed9dbfe00f8c: Login # Login
    5da67f8c-ab63-473a-8a06-56f08001fc9c: 'Group Four Handle' # Group Four Handle
    6b9c8402-39e7-4103-b54e-394a286410b8: Lat # Lat
    6c53837c-f9da-43a9-8b85-6b133dce6995: Asset # Asset
    6f2b710a-6864-4280-8547-363a00213e8e: Members # Members
    6f166b0f-35de-422d-b4b1-66441ce46253: Rsvp # Rsvp
    7c6ffd50-236d-41ef-b9b0-ed933128ead8: Locations # Locations
    7c26f0a0-ef03-4022-b353-239865ffcdb5: 'Privacy Policy' # Privacy Policy
    8dec35ce-7bad-4407-bbc3-56adc9cccc4a: Login # Login
    9b440915-1a29-471d-9ebe-88c6673362e7: Map # Map
    9bc06dfa-790d-40dc-b656-17de5c920ef5: Program # Program
    9cf5f394-9490-4101-bdc7-5f09654f53e7: Thumbnail # Thumbnail
    9ee4a793-9be1-424c-b7c5-3e55b24bd669: New # New
    9f819326-c617-42fe-a427-a0c843eb9312: POI # POI
    13a8868b-e382-483f-9f64-0743e959d4b9: 'Text Field' # Text Field
    20d23889-9805-4910-b96d-d69c5b2341ed: Route # Route
    21c100fa-b14d-4c5a-b30a-f1f28bc91e6d: Register # Register
    22ded96b-de85-4414-a36e-ba62898a3e19: 'Map Bearing' # Map Bearing
    28df0b76-c9f0-4d20-8ca1-a15c637783ea: 'Route Name' # Route Name
    29af6c74-049e-465f-97f6-c25132abd027: 'Marker Size' # Marker Size
    41bce798-33f6-4c59-9ccb-7cce0cc31032: 'Map Centre' # Map Centre
    49d0005e-81de-4029-985b-30b90f013162: 'Map PostalCode' # Map PostalCode
    51bd5b4e-75c4-42a1-b1b5-1827613ecaef: Address # Address
    51c71de1-cd5f-45b5-8c0f-406dc42a9945: Founders # Founders
    54d7b784-36c0-4673-ac81-61eb4fec1591: Date # Date
    62bbfaa1-afe7-4d10-86d1-a4f1f257284d: 'Marker thumbnail placeholder' # Marker thumbnail placeholder
    64f81d1c-c242-4549-8d9f-19d9974d28c7: User # User
    72b5edf2-4be1-4151-82cd-8fecab941ea9: Default # Default
    76b8abf5-b5a7-4316-b76f-042fd9b0e526: Map # Map
    84f5e1d4-3d01-4be8-82df-2de9132f6b6b: 'Link Text' # Link Text
    85b7a402-007c-4598-b380-2ed317ce08bc: LinkedIn # LinkedIn
    90a58fe8-93e7-4f43-a79c-f92d1076f9c0: 'Glue locations' # Glue locations
    94b2ace0-9736-4772-8b51-5ad1c118ba9b: Register # Register
    97d0a464-bcc8-4a07-bcfc-f91437d0d73d: 'Hub Suffix' # Hub Suffix
    0135bceb-e438-4587-afb0-58be11f4b6ec: 'Opening Times' # Opening Times
    143e2045-0511-4445-8b26-cda06d142159: 'Age Group' # Age Group
    164bc9a4-5b57-4fb1-b7e2-9fb883aebc34: 'Phone number' # Phone number
    224d134b-3e57-4e94-a6b0-97108c266b94: Hub # Hub
    425e9499-b42c-4458-b1a8-07a316d4e328: Profession # Profession
    455ecd20-d076-49c7-8fc6-57888147a961: Zip # Zip
    462e7888-6a24-4c61-b3f1-faaec6bc45ad: 'Link Destination' # Link Destination
    623f54ba-640b-4690-bb9d-fffae8471ed9: Twitter # Twitter
    687bb273-50a1-471a-b240-7ccc88e88288: 'Map Pitch' # Map Pitch
    730ad796-ff23-490f-8887-4f2390c57f97: 'Group Two Handle' # Group Two Handle
    767ce7ff-b004-4bb8-a476-13d97b25fc2b: 'Contact Form' # Contact Form
    777e0919-b16b-490f-a586-9bc96baf546d: Time # Time
    2603f45d-35b6-49c5-8c18-392fc415f0ab: 'Marker Matrix' # Marker Matrix
    3991b82d-f96d-4096-979e-357725ad6db4: Asset # Asset
    5415fc47-c06d-49ba-b50c-902b3db86c4b: Default # Default
    6476a883-533b-45e3-8d3d-0dd262e7c5b5: Markers # Markers
    8338e071-a901-4ca5-80a4-ea0b0e33acec: Collective # Collective
    8634fab2-bde5-4665-80a8-324c56cb1c35: 'Web Images' # Web Images
    8809cf4a-41fd-49bf-9e6c-01bb347d9a21: Token # Token
    8849fcad-9c3c-407d-be47-dc023f96bfb0: 'Social Media Image' # Social Media Image
    20650a18-d4f6-482d-8d9e-6e0c30e087a7: Venue # Venue
    30663d7d-536d-454c-99fd-820672718f4e: Routes # Routes
    53354b75-ade8-4058-a3d9-88355797c897: Email # Email
    294337b5-643e-4cd3-92c7-01c2dade26ce: 'Map Zoom' # Map Zoom
    629498d0-534c-4a2a-996f-82b75a6f1864: Member # Member
    668738fd-0979-4b4f-9baa-b83f18974c13: 'Terms & Conditions' # Terms & Conditions
    803445eb-0364-48f9-9808-cf5c51985216: General # General
    830820ed-79d9-4d46-9e86-4134fc2b8d2b: Country # Country
    1972499d-a514-4921-81a0-426f9e57f7b2: 'Program Type' # Program Type
    24188079-a4ae-442c-a887-c038437ae289: Event # Event
    a048000e-e0dc-476a-b101-76110a53ebe6: 'Marketing Permissions' # Marketing Permissions
    a1a284ed-b660-4132-9e98-a7af09a3cc32: 'Rich Text' # Rich Text
    acb4d8ea-f708-4993-846b-d1e591d442ff: 'Route Group' # Route Group
    ae91170d-e3ba-466f-92ff-05269557039f: 'Glue events' # Glue events
    afaddf10-8b46-42cc-a4c2-3842de0d8fe2: 'Company name' # Company name
    b7b0394d-62fe-4e1d-9214-0026ddff54bd: 'Special Program' # Special Program
    b8f74062-ae64-4520-a7ed-fe4272ee4456: 'User Avatars' # User Avatars
    b293ae54-2bba-485d-814f-af219d5fc776: 'HUB slide duration' # HUB slide duration
    bab14c41-889d-40ef-bed6-cb4f4fc062ac: Route # Route
    bcc4aab8-13e9-4efc-a464-78c59170a854: 'Large Text Field' # Large Text Field
    bd5e2840-24bf-449d-8949-c7c8429d4018: Title # Title
    c0f16670-30a8-4b0d-93c2-bc35b31ba3ee: 'Public Schema' # Public Schema
    c07e5122-84e3-403c-ba29-8c08760aa3ee: Centre # Centre
    c5fb5f28-2f93-4a73-bcd6-9c57ee22f86f: $SITE_NAME # $SITE_NAME
    c8adfe4a-01be-4ef5-a6ea-1dd05dbdf07e: DateTable # DateTable
    c478aed5-aad0-4896-8cd6-9f036a0fb5f2: Members # Members
    c6635e8d-466b-4c83-a690-b8d9596ed2ee: Guests # Guests
    c700366d-c002-43b2-b7ce-f8dd82c7afa8: Participants # Participants
    c2872290-8524-4632-b215-9fe238402822: Asset # Asset
    cab00bb9-f285-41cd-9dfc-6b675f5c4817: Map # Map
    cb9b4037-71ad-4f2d-b47e-a020160c2a5c: 'Edit page' # Edit page
    cd1f3a93-b4a0-445b-97ab-b378129dbb74: 'Map Address' # Map Address
    cdfc6d46-fdd1-4bdf-b53b-7f44b84230a5: Stylesheet # Stylesheet
    ce4c8a98-5c1f-4d39-bbf0-6bfd5fd4ba32: Subtitle # Subtitle
    ce975126-df40-409e-97f4-7b3f95382b3b: 'Terms & Conditions' # Terms & Conditions
    d5fda0ac-6099-4e3c-8804-1a5fb5178809: Hub # Hub
    d7f79a98-5851-4ca8-8097-74672ff95134: Facebook # Facebook
    d3712c0e-7898-4805-8cee-c9b619cf6a46: 'One Word' # One Word
    d441938f-e95b-4f5f-8661-9c03238e51e7: 'Collective Suffix' # Collective Suffix
    e4e090a3-6fa6-47ce-a91b-8171b1a84a58: 'Special Program' # Special Program
    e6ea2a09-6abe-4046-8a6f-c483f1d58716: Common # Common
    e3480c4d-8e7a-4311-af43-7a686e25d7a0: Website # Website
    e49004dc-97e1-4069-852d-2b53e7f5b8a1: Founder # Founder
    ecf5bd66-ad84-4640-b9b2-cf4172f1b84d: 'Group One Handle' # Group One Handle
    f0917fc5-6089-45ec-a4e2-c442ce4726a2: Package # Package
    f46c926b-268c-4328-ad61-180b55bea62e: City # City
    f78b3456-eb39-4e20-9c93-c091a09a1fc4: 'Privacy Policy' # Privacy Policy
    fa5f1e79-50ce-45ec-9e91-44a272e11387: Asset # Asset
    fe460ddb-f48c-4b81-bf14-1bb2e54c4e72: 'Hub Minimum Count' # Hub Minimum Count
plugins:
  connect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ":root {\r\n    --primary-hue: 235;\r\n    --primary-color: hsl(var(--primary-hue), 93%, 54%);\r\n    --primary-extra: hsl(var(--primary-hue), 93%, 62%);\r\n}\r\n\r\n.btn.submit:not(.disabled):not(.inactive):not(.loading).hover, .btn.submit:not(.disabled):not(.inactive):not(.loading):focus, .btn.submit:not(.disabled):not(.inactive):not(.loading):hover {\r\n    background-color: var(--primary-extra) !important;\r\n}\r\n"
      cacheBusting: true
      cssFile: ''
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: true
      redirectToEntry: true
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: Europe/Amsterdam
