fieldLayouts:
  09dbd413-0b81-440d-8db0-2a3ffe880160:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5b1e8713-7a27-46ed-a407-e926769d89e2 # Colour
            instructions: null
            label: 'Yearly colour'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50912bbe-ab77-41dc-9b5f-34db73cb9b62
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c8adfe4a-01be-4ef5-a6ea-1dd05dbdf07e # DateTable
            instructions: null
            label: 'Event Dates'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca6a8a8a-f169-43fd-8a94-c655a1d05b0c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f6049f8-db41-426e-86a4-196457c3e028 # Slug
            instructions: 'A link pointing towards a page (usually home) always shown in the header'
            label: 'Return Link'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0480ac6-1192-4436-91d3-187a12402861
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d3712c0e-7898-4805-8cee-c9b619cf6a46 # One Word
            instructions: 'The text that''s be shown in the return link'
            label: 'Return name'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbac7a58-b356-4277-bbb5-783933bf3018
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bd5e2840-24bf-449d-8949-c7c8429d4018 # Title
            instructions: 'Title shown in the browser tab'
            label: 'Site title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6122ad1-a9fe-46fb-8f5f-d4d7323f3861
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 80edcb8c-54e9-470f-bd53-7ecb17215263
        userCondition: null
handle: event
name: Event
sortOrder: 3
