fieldLayouts:
  3213bd96-48e7-4295-af0b-5dcdaf8215e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 00602bc8-2fab-4442-bff1-e6af501f1470 # Socials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 022b7632-7c34-4af8-bbba-e00f322d4200
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 49ca19d3-7243-4ebb-9408-fda5f92807d5
        userCondition: null
handle: footer
name: Footer
sortOrder: 5
