fieldLayouts:
  010da39f-55ac-44a7-9f71-0f7cc998f69b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2e1ecccd-c3ca-4249-b239-5faa3edb6606
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7498566d-c72d-409a-99e8-6b93dbb319f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8809cf4a-41fd-49bf-9e6c-01bb347d9a21
            instructions: 'Public mapbox API token'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 374d8620-01b8-435d-af00-72b7e015a77d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdfc6d46-fdd1-4bdf-b53b-7f44b84230a5
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b75aef1a-7521-439c-ac9e-362bd43baeb1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41bce798-33f6-4c59-9ccb-7cce0cc31032
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd39d536-bdd2-429f-b8de-708bc86a5aa4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 294337b5-643e-4cd3-92c7-01c2dade26ce
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96ab4119-5d91-454e-922c-effdef0f1461
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 687bb273-50a1-471a-b240-7ccc88e88288
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 482f4664-2663-456f-9fb9-866fa9747723
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22ded96b-de85-4414-a36e-ba62898a3e19
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 415a5056-9aad-43a6-a84f-27a2224b2f70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2603f45d-35b6-49c5-8c18-392fc415f0ab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ce3c127-cd74-4280-b660-4266f4b7e578
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62bbfaa1-afe7-4d10-86d1-a4f1f257284d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86231388-588f-4862-98a2-e4dcca34f100
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 29af6c74-049e-465f-97f6-c25132abd027
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 198a86fb-63f2-4de2-8766-064062b51472
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fe460ddb-f48c-4b81-bf14-1bb2e54c4e72
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 231004de-76d9-4eca-9a4f-2f1c178b0250
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97d0a464-bcc8-4a07-bcfc-f91437d0d73d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb021815-2cb1-49d0-b8d7-6470c680cb65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d441938f-e95b-4f5f-8661-9c03238e51e7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4a43ab7-c8a7-448a-9be3-119c393a75c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b293ae54-2bba-485d-814f-af219d5fc776
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f27b5259-116b-488c-a0e7-97ccc82dbbee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ecf5bd66-ad84-4640-b9b2-cf4172f1b84d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9aadfbc-0e19-4f21-9974-54ee01dfe765
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 730ad796-ff23-490f-8887-4f2390c57f97
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b222034-ea66-498e-979a-08cab74b7491
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3fc5f4d1-e130-417e-8f41-29bb276bfbb2
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ff6fcd4-94ae-4db9-93cd-758e1ef47fad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5da67f8c-ab63-473a-8a06-56f08001fc9c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e754675-97fa-42c4-a48a-e9bd88b1a5e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 30663d7d-536d-454c-99fd-820672718f4e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdbe2303-0566-44fc-b858-3897044b267a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 883beb3e-a9fd-49da-b0eb-82a74ea99261
        userCondition: null
handle: map
name: Map
sortOrder: 6
