fieldLayouts:
  010da39f-55ac-44a7-9f71-0f7cc998f69b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8809cf4a-41fd-49bf-9e6c-01bb347d9a21 # Token
            instructions: 'Public mapbox API token'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 374d8620-01b8-435d-af00-72b7e015a77d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdfc6d46-fdd1-4bdf-b53b-7f44b84230a5 # Stylesheet
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b75aef1a-7521-439c-ac9e-362bd43baeb1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 294337b5-643e-4cd3-92c7-01c2dade26ce # Map Zoom
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96ab4119-5d91-454e-922c-effdef0f1461
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 687bb273-50a1-471a-b240-7ccc88e88288 # Map Pitch
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 482f4664-2663-456f-9fb9-866fa9747723
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22ded96b-de85-4414-a36e-ba62898a3e19 # Map Bearing
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 415a5056-9aad-43a6-a84f-27a2224b2f70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d152d4b-1ee3-4f95-bca3-97ab4af05e68 # Route Marker Icon
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b5b63da-07b3-4022-81e0-2490e542f885
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4bcb26e-0946-40a4-a3e0-1d73c3971119 # Locations Marker Icon
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3019a8ba-8eea-4581-be19-dbd6cdfbcec2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 29af6c74-049e-465f-97f6-c25132abd027 # Marker Size
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 198a86fb-63f2-4de2-8766-064062b51472
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 30663d7d-536d-454c-99fd-820672718f4e # Routes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdbe2303-0566-44fc-b858-3897044b267a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 883beb3e-a9fd-49da-b0eb-82a74ea99261
        userCondition: null
handle: map
name: Map
sortOrder: 6
