defaultPlacement: end
enableVersioning: true
handle: dailyProgram
name: 'Daily Programs'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c5fb5f28-2f93-4a73-bcd6-9c57ee22f86f: # Glueweb Amsterdam
    enabledByDefault: true
    hasUrls: true
    template: dailyProgram/_entry.twig
    uriFormat: 'daily-program/{slug}'
type: channel
